export const PUSH_OPERATION = "PUSH_OPERATION";
export type PUSH_OPERATION = typeof PUSH_OPERATION;

export const DELETE_OPERATION = "DELETE_OPERATION";
export type DELETE_OPERATION = typeof DELETE_OPERATION;
