export const PUSH_OPERATION = "PUSH_OPERATION";
export type PUSH_OPERATION = typeof PUSH_OPERATION;

export const CONSUME_OPERATION = "CONSUME_OPERATION";
export type CONSUME_OPERATION = typeof CONSUME_OPERATION;
