export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export type ADD_NOTIFICATION = typeof ADD_NOTIFICATION;

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export type UPDATE_NOTIFICATION = typeof UPDATE_NOTIFICATION;

export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export type DELETE_NOTIFICATION = typeof DELETE_NOTIFICATION;

export const BULK_ADD_NOTIFICATIONS = "BULK_ADD_NOTIFICATIONS";
export type BULK_ADD_NOTIFICATIONS = typeof BULK_ADD_NOTIFICATIONS;

export const BULK_UPDATE_NOTIFICATIONS = "BULK_UPDATE_NOTIFICATIONS";
export type BULK_UPDATE_NOTIFICATIONS = typeof BULK_UPDATE_NOTIFICATIONS;

export const BULK_DELETE_NOTIFICATIONS = "BULK_DELETE_NOTIFICATIONS";
export type BULK_DELETE_NOTIFICATIONS = typeof BULK_DELETE_NOTIFICATIONS;
